/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Vuesax Theme",
  "description": "Vuesax",
  "base": "/",
  "pages": [
    {
      "title": "Hello VuePress",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2cee5094",
      "path": "/"
    }
  ],
  "themeConfig": {
    "headerTitle": "Prueba",
    "website": "https://github.com/lusaxweb/vuesax",
    "repo": "lusaxweb/vuesax",
    "nav": [
      {
        "text": "about",
        "link": "/about.html"
      },
      {
        "text": "girls",
        "link": "/girls.html"
      },
      {
        "text": "donate",
        "link": "/donate.html"
      },
      {
        "text": "tag",
        "link": "/tag/"
      },
      {
        "text": "category",
        "link": "/category/"
      }
    ]
  }
}