export { default as vsButton } from './vsButton/Base/index'
export { default as vsButtonGroup } from './vsButton/group/index'
export { default as vsAlert } from './vsAlert/Base/index'
export { default as vsInput } from './vsInput/Base/index'
export { default as vsCheckbox } from './vsCheckbox/Base/index'
export { default as vsSwitch } from './vsSwitch/Base/index'
export { default as vsSelect } from './vsSelect/Base/index'
export { default as vsOption } from './vsSelect/Option'
export { default as vsOptionGroup } from './vsSelect/OptionGroup'
export { default as vsAvatar } from './vsAvatar/Base/index'
export { default as vsAvatarGroup } from './vsAvatar/Group'
export { default as vsRadio } from './vsRadio/Base/index'
// new component slot
